version: "3.8"
services:
  backend:
    build: backend/.
    image: devops_backend:v1
    environment:
      MYSQL_HOST: mysql
      JWT_SECRET_TOKEN: your_secret_token_here
      CORS_ORIGIN_REGEX: https://frontend:3002
      #CORS_ORIGIN_REGEX: http([s])?:\/\/frontend:3002
    healthcheck:
      test: [ "CMD", "ls" ]
      interval: 10s
      timeout: 10s
    depends_on:
      - mysql

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    image: devops_frontend:v1
    environment:
      SERVER_ORIGIN: backend:3001
    ports:
      - 80:3002
    healthcheck:
      test: [ "CMD", "ls" ]
      interval: 10s
      timeout: 10s
    depends_on:
      - backend

  mysql:
    image: mysql_utf8mb4:5.7
    build: db/.
    volumes:
      - devops-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tradeoffer_db
    healthcheck:
      test: [ "CMD", "ls" ]
      interval: 10s
      timeout: 10s

  adminer:
    image: adminer
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "ls" ]
      interval: 10s
      timeout: 10s
    depends_on:
      - mysql

volumes:
  devops-mysql-data: